### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by rawenloft** [alexnest-ua/auto_mhddos_alexnest#1]
Hello everyone, tool stop working with following error:

> Traceback (most recent call last):
  File "/root/mhddos_proxy/runner.py", line 438, in <module>
    start(
  File "/root/mhddos_proxy/runner.py", line 352, in start
    update_proxies(period, targets, max(total_threads, THREADS_PER_CORE), proxy_timeout)
  File "/root/mhddos_proxy/runner.py", line 161, in update_proxies
    future_to_proxy.update({
  File "/root/mhddos_proxy/runner.py", line 162, in <dictcomp>
    executor.submit(proxy.check, resolved_target, proxy_timeout): proxy
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 170, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 193, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Looks like last modification of mhddos_proxy brorke down your tool. Check please for all of us, its the best I found for droplet usage. Слава УкраЇні!

**Comment by rawenloft** [comment]
Manually added mhddos_proxy and MHDDoS. No changes, not working :(

**Comment by rawenloft** [comment]
Observed that after one cycle tool is not restarting, but continue with over 100% (abt133% it crashes)

**Comment by alexnest-ua** [comment]
> Hello everyone, tool stop working with following error:
> 
> > Traceback (most recent call last):
> > File "/root/mhddos_proxy/runner.py", line 438, in 
> > start(
> > File "/root/mhddos_proxy/runner.py", line 352, in start
> > update_proxies(period, targets, max(total_threads, THREADS_PER_CORE), proxy_timeout)
> > File "/root/mhddos_proxy/runner.py", line 161, in update_proxies
> > future_to_proxy.update({
> > File "/root/mhddos_proxy/runner.py", line 162, in 
> > executor.submit(proxy.check, resolved_target, proxy_timeout): proxy
> > File "/usr/lib/python3.9/concurrent/futures/thread.py", line 170, in submit
> > self._adjust_thread_count()
> > File "/usr/lib/python3.9/concurrent/futures/thread.py", line 193, in _adjust_thread_count
> > t.start()
> > File "/usr/lib/python3.9/threading.py", line 874, in start
> > _start_new_thread(self._bootstrap, ())
> > RuntimeError: can't start new thread
> 
> Looks like last modification of mhddos_proxy brorke down your tool. Check please for all of us, its the best I found for droplet usage. Слава УкраЇні!

What command are you runnung? Looks like too many running processes (option `-t`)  at the same time

Send me pls characteristics of your processor, so then I can give you the most optimal command for your configuration 

And try to upgrade Python to 3.10 version

**Comment by rawenloft** [comment]
All cleared by installation python 3.10. Thank you very much! All works fint
