### ISSUE TITLE
не працюэ

### ISSUE THREAD

**Issue by ghost** [alexnest-ua/auto_mhddos_alexnest#10]
Вітаю. Встановив, але у кінці вилазе красна строка з помилкою і миттєво ісчезає. І так по кругу. Программа не працює.
При запуску сетапу щось успішно видалило із системи! Потім знов щось не змогло знайти.
Вимушен користуватись звичайним мшдд-ос проксі.

**Comment by ifest1val** [comment]
> Вітаю. Встановив, але у кінці вилазе красна строка з помилкою і миттєво ісчезає. І так по кругу. Программа не працює. При запуску сетапу щось успішно видалило із системи! Потім знов щось не змогло знайти. Вимушен користуватись звичайним мшдд-ос проксі.

Ви можете зняти відео, на телефон, та прочитати.

**Comment by alexnest-ua** [comment]
@sova32 хмм, дійсно не завадив би запис екрану, щоб зрозуміти, що саме за помилка, бо у мене червоного тексту в скрипті ніде немає

А яка у вас Операційна система? Яку саме команду запускаєте?

**Comment by ghost** [comment]
запрацювало. треба було поставити галку що файл "исполняемый"

вс, 8 мая 2022 г. в 10:53, Слава Украине ***@***.***>:

**Comment by ghost** [comment]
запрацювало. треба було поставити галку у свойствах що файл исполняемый

вс, 8 мая 2022 г. в 10:53, Слава Украине ***@***.***>:

**Comment by alexnest-ua** [comment]
підкажіть хоч на якій Операційній системі це було...

**Comment by ghost** [comment]
opensuse thumblweed
я перевірив на debian то по інструкції все працює
не запрацювало на opensuse thumbleweed мабуть це особливість самої системи,
вона поідеї відмовляється запускати файли в свойствах яких не стоїть
галочка "исполняемый".

і ще одне. у самому коді runner.py я добавив строку щоб видавало список
проксі. так я пробував у firefox підключатись через ці проксі і в мене не
вийшло. таке відчуття, що утіліта працює в холосту тобто пакети
відправляються (майже до 10-и мегабіт) але до цілі не доходять. і прийом
майже нуль. кілабіт 20 максимум.


вс, 8 мая 2022 г. в 17:09, alexnest-ua ***@***.***>:

**Comment by ghost** [comment]
було добре коли программа сама шукала проксі і перевіряла їх, а не брала
вже готовий список.

вс, 8 мая 2022 г. в 17:09, alexnest-ua ***@***.***>:

**Comment by alexnest-ua** [comment]
1) Я тестував скрипт лише на Ubuntu 20.04 та Kali, тому не можу знати, що там на інших непопулярних Лінуксах, де можуть бути не всі потрібні пакети доступні
2) Коли останній раз ви робили таку перевірку проксі?
3) Я думаю ви просто не вмієте налаштовувати проксі для машини / браузера, ось 100% перевірка чи реально міняється ІР: `curl --proxytunnel --proxy "http://45.190.249.100:8080" http://ident.me`
4) Програма так і робить - кожну годину проганяє більше 300 000 різних проксі, і з них бере лише робочі (увесь список ~25 000), а потім юзерам віддає по 200 штук за раз

**Comment by ghost** [comment]
Перевірку проксі через браузер я робив як тільки отримував список проксі.
так - я не вмію налаштовувати проксі для системи. в інтернеті нормальної
документації по якій би вдалось підключитись теж не знайшов. ввожу
налаштування проксі але нічого не робить. айпі не змінюється.

пн, 9 мая 2022 г. в 00:58, alexnest-ua ***@***.***>:

**Comment by ghost** [comment]
***@***.***:~> curl --proxytunnel --proxy http://45.190.249.100:8080
http://ident.me
***@***.***:~>
і що тут можна зрозуміти. що трапилось з моєю консоллю?
можете дати нормальний приклад або урок як підключитись до проксі? мені з
самого початку війни ніхто не може відповісти на це питання. в інтернеті
нічого не працює.
допоможіть будьласка. в мене Операционная система: openSUSE Tumbleweed
20220507
Версия KDE Plasma: 5.24.5
Версия KDE Frameworks: 5.93.0
Версия Qt: 5.15.2
Версия ядра: 5.17.4-1-default (64-бита)
Графическая платформа: X11
ввожу в налаштунках через яст ір та порт і отримую помилку. через настройки
системи у кде нічого не працює.

пн, 9 мая 2022 г. в 00:58, alexnest-ua ***@***.***>:

**Comment by alexnest-ua** [comment]
Для вашої Операційної системи, на жаль, не підкажу

Ставте Ubuntu 20.04 :)
