### ISSUE TITLE
Синхронізація цілей

### ISSUE THREAD

**Issue by kirealll** [alexnest-ua/auto_mhddos_alexnest#11]
Ви зробили класний скрипт, але він використовує власний список цілей, хоча заявлено, що цілі беруться з https://t.me/ddos_separ. Сьогодні ddos_separ атакує сайти оренди нерухомості і банки, а ваш скрип атакує транспорт. Будь ласка, зробіть так, щоб за замовчуванням mhddos_proxy запускався з аргументом --itarmy. Тоді не буде цього розсинхрону цілей і вам не треба буде підтримувати окремий файл з цілями.

**Comment by alexnest-ua** [comment]
Це робиться спеціально, щоб тримати в ауті одночасно декілька різних цілей. Бо якщо ми будемо відходити від старих - вони будуть собі преспокійно жити.
Лише --itarmy не буде, бо у них восновному у 3 рази менше цілей ніж у https://t.me/ddos_separ
ось для прикладу сьогодніші цілі - банки з --itarmy:
`[20:15:59 - INFO] Завантажено конфіг https://gist.githubusercontent.com/ddosukraine2022/f739250dba308a7a2215617b17114be9/raw/mhdos_targets_tcp_v2.txt на 172 цілей`
а ось з https://raw.githubusercontent.com/alexnest-ua/targets/main/special/archive/banks/banks_l7:
`[20:16:53 - INFO] Завантажено конфіг https://raw.githubusercontent.com/alexnest-ua/targets/main/special/archive/banks/banks_l7 на 516 цілей`

IT Army просто боїться атакувати великі сайти(або сайти які мають хоч якісь зв'язки зарубіжні по типу РайффазенБанку),а ми не боїмося.

Загалом: списки правильні, ми не можемо дозволити нормально працювати старим сайтам, тому у списку завжди підтримується 2-3 різні сфери
