### ISSUE TITLE
Exclude UDP targets when --vpn is not used

### ISSUE THREAD

**Issue by 0zhu** [alexnest-ua/auto_mhddos_alexnest#2]
runner_targets_new file contains some udp targets.
When the script choose those them, 'Атака без проксі переконайтеся що ви анонімні' warning is displayed during script run.
Maybe it worth excluding udp targets when --vpn flag is not used to prevent extra risks?

**Comment by alexnest-ua** [comment]
> runner_targets_new file contains some udp targets. When the script choose those them, 'Атака без проксі переконайтеся що ви анонімні' warning is displayed during script run. Maybe it worth excluding udp targets when --vpn flag is not used to prevent extra risks?

--vpn in order to use your ip, not a proxy, but udp attacks themselves use your real ip, so the --vpn flag will not help in this case

well, I'd rather just delete the UDP targets, because they eat a lot of traffic

thanks for your Issue
