### ISSUE TITLE
Звідки цілі?

### ISSUE THREAD

**Issue by Kerber0ss** [alexnest-ua/auto_mhddos_alexnest#3]
Звідки беруться цілі? Шось у файлі зараз стільки цілей шо результату точно не буде. Частина є тих шо атакує кіберармія, частина шо козаки, частина зовсім старих. Розпиляємося, а краще згуртуватись.

**Comment by alexnest-ua** [comment]
> Звідки беруться цілі? Шось у файлі зараз стільки цілей шо результату точно не буде. Частина є тих шо атакує кіберармія, частина шо козаки, частина зовсім старих. Розпиляємося, а краще згуртуватись.

проблема не в гуртуванні, а тому, що якщо одні цілі будуть усі бити, то проксі ж не нескінченні, а сайти їх кидають у блек-лист, тому для більшої дестабілізації РФ краще бити декілька різних - менших цілей

А взагалі, якщо сайт реально можно положити, то він у перші 2-3 хвилини лягає повністю навіть від 100 юзерів, просто великі сайти набагато швидше підіймають і блочать ІРшники, ніж малі, які будуть ще довго лежати після атаки
