### ISSUE TITLE
Помилка встановлення пакетів на старих версіях Linux(Ubuntu)

### ISSUE THREAD

**Issue by trinitiwowka** [alexnest-ua/auto_mhddos_alexnest#8]
[27-04-2022 21:49:46] - DDoS is up and Running, next update of targets list in 20m ...
Traceback (most recent call last):
  File "runner.py", line 5, in <module>
    from queue import SimpleQueue
ImportError: cannot import name 'SimpleQueue'

**Comment by alexnest-ua** [comment]
Яка версія Операційної системи?

**Comment by trinitiwowka** [comment]
Ubuntu 18.04, при этом на соседнем Ubuntu 20.04 все работает хорошо

**Comment by alexnest-ua** [comment]
Усе що нижче 20.04 - не підходить
