### ISSUE TITLE
Проблемы с Docker Dekstop

### ISSUE THREAD

**Issue by Fadeto** [alexnest-ua/auto_mhddos_alexnest#9]
При запуске из докера auto_mhddos_alexnest подвисает system explorer, хотя диспечер задач и все другие процессы отзываються нормально. Даже при рендере при 100% нагрузке на проц такого нет. В диспечере рисует около 15-70% процентов загрузки процессора на system explorer, хотя по умолчанию он ест не более 0,1-1%. Время обновления в system explorer выставлено на среднее около 3сек.

**Comment by alexnest-ua** [comment]
Это проблема Docker`а, ибо это целая Виртуальная машина, так происходит с любым с любыми скриптом запущенном на нем. Вот такие у меня показатели на i9-11900f с Докером:
![image](https://user-images.githubusercontent.com/74729549/166191212-a1243e42-bb32-4641-b9de-0f3d1f231a83.png)
а вот такие через Python:
![image](https://user-images.githubusercontent.com/74729549/166191237-53778c01-e947-4b3c-be25-a0e4e9e3c36d.png)

Потому, если хотите живой процессор, а не камень, рекомендую уходить от Докера к установке напрямую:
Windows: https://github.com/alexnest-ua/runner_for_windows
Linux: https://github.com/alexnest-ua/auto_mhddos_alexnest
